### ISSUE TITLE
Unable to render this definition

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [scottie1984/swagger-ui-express#187] opened 2020-05-22 11:25 UTC
I have 
```
swagger: 2.0
```
defined in yaml file and it was working fine for about 2 years. Recently, it failed to render:
<img width="1660" alt="Screen Shot 2020-05-22 at 3 21 50 PM" src="https://user-images.githubusercontent.com/11527341/82663057-04c3c400-9c40-11ea-9872-04c96b248f95.png">

I have found that it works if I remove 4 definitions from yaml file, but these 4 looks correct and those were working for 2 years.

**Comment by AlbertHambardzumyan** [comment] 2020-05-22 11:43
I found some pattern:
I have `entries` property in these definition, and if I change those to something else, then it works.

Looks like recently `entries` became a keyword.
Any thoughts ?

**Comment by AlbertHambardzumyan** [comment] 2020-05-22 12:23
Also, I have found that  "swagger-ui-express": "4.1.3" does not complain about `entries` property and works fine.

**Comment by scottie1984** [comment] 2020-11-14 10:22
Mostly likely this is due to swagger-ui changes. Closing for now as the issue is quite old. Please feel free to reopen if needed

**Closed by scottie1984** 2020-11-14 10:22 UTC
