### ISSUE TITLE
Expose the internal swagger spec

### ISSUE THREAD

**Issue by mwallnoefer** [scottie1984/swagger-ui-express#200] opened 2020-07-08 19:23 UTC
I use the official Swagger JS client (*swagger-js*) which requires direct access to the JSON/YAML spec as shown here: https://github.com/swagger-api/swagger-js/blob/master/docs/usage/installation.md#unpkg.

I resolved this by using the following custom path handler: `/` resolves to the Swagger UI, `/swagger.json` passes back the raw JSON spec. No idea if this is the best solution, if yes, feel free to publish it in the *README.md*.  
```
// could also be served under '/api-docs'
app.use('/', (req, res, next) => {
    swaggerDocument["host"] = req.get('host')
    req.swaggerDoc = swaggerDocument
    if (req.path.endsWith('/swagger.json'))
      res.send(swaggerDocument)
    else
      next()
}, swaggerUi.serve, swaggerUi.setup())
```

**Comment by mwallnoefer** [comment] 2020-09-23 17:54
Any news?

**Comment by scottie1984** [comment] 2020-11-14 10:25
Duplicate of https://github.com/scottie1984/swagger-ui-express/issues/194. Please look there for a workaround. I will look to see if I can add anything to the module in the meanwhile

**Closed by scottie1984** 2020-11-14 10:25 UTC
