### ISSUE TITLE
Issue when deploying to AWS Beanstalk - Node.js - Nginx

### ISSUE THREAD

**Issue by zenzjtech** [scottie1984/swagger-ui-express#226] opened 2020-11-01 11:43 UTC
Hello, 

I'm deploying [this app](https://github.com/hagopj13/node-express-mongoose-boilerplate) to Beanstalk of which the underlying EC2 instance uses Node.js v12 and Nginx.

When the app is run at my localhost, **swagger docs** is rendered normally as expected.

But when deploying to Beanstalk, the result is `timeout`
The reason, as I've been inspecting until now, is that all of the accompanying _resource files_ are loaded from _https_ protocol, which is not available at Beanstalk server, while the source _index.html_ is loaded from _http_ protocol.

Note that the protocol my beanstalk is _http_, as you could see from the screenshot.

![image](https://user-images.githubusercontent.com/10528635/97801669-f9ee7000-1c70-11eb-82a2-3ff91b41af68.png)

Related source code

- [swaggerDef.js and swagger.yml](https://github.com/hagopj13/node-express-mongoose-boilerplate/tree/master/src/docs)
- [routes.js](https://github.com/hagopj13/node-express-mongoose-boilerplate/blob/master/src/routes/v1/index.js)

Thank you for any helps!

**Comment by weylermaldonado** [comment] 2020-11-02 21:03
Same problem, did you figure out any solution?

**Comment by zenzjtech** [comment] 2020-11-03 00:09
> Same problem, did you figure out any solution?

I have to temporarily posting swagger -> postman json file, and use postman web for publishing docs.

**Comment by scottie1984** [comment] 2020-11-14 11:25
I’m not sure the issue is with this module or how it can be fixed. I don’t see any references to https in the code.

I will close this for now - please feel free to reopen if you can provide further details or you can pinpoint a fix

**Closed by scottie1984** 2020-11-14 11:25 UTC
