### ISSUE TITLE
Internationalization of docs

### ISSUE THREAD

**Issue by martinszy** [scottie1984/swagger-ui-express#133] opened 2019-06-26 00:02 UTC
Hello, is it possible to have multiple languages for the documentation?

We're trying to be multilingual in our docs and I don't see a way to do that with swagger-ui-express.

Thanks.

**Comment by scottie1984** [comment] 2019-06-26 08:43
There is an open (and known) issue with swagger-ui regarding internationalization:

https://github.com/swagger-api/swagger-ui/issues/2488

Once it is resolved in swagger-ui it should make its way straight to swagger-ui-express (very rarely swagger-ui-express has to be updated but if it does post here).

**Comment by martinszy** [comment] 2019-06-26 13:34
Oh, thanks!

**Comment by shockey** [comment] 2019-06-26 14:02
FWIW, the core team won't be able to get this done in Swagger UI in the near future -- @martinszy, happy to chat if you're feeling up to making a PR for it.

**Comment by endomorphine** [comment] 2019-07-22 15:33
@shockey there is some PR https://github.com/swagger-api/swagger-ui/pull/5385

**Closed** 2020-02-22 16:04 UTC

**Comment by martinszy** [comment] 2020-02-22 21:36
Hello, sorry to ask but this was closed without merging the PR, was this fixed? Is the PR going to be merged?
We would like to use this too.

**Comment by scottie1984** [comment] 2020-02-22 21:42
The PR relates to a different project - as the issue is with swagger-ui which is a dependency of this module. Happy to keep it open if needed but it should be tracked there.
